gcp_dbt_project:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: gcp-dbt-454911
      dataset: dbt_staging
      location: europe-southwest1
      threads: 1
      job_execution_timeout_seconds: 600
  target: dev